# Generated by Django 4.2.3 on 2023-07-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hads_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hadsquestion',
            name='subscale',
            field=models.CharField(choices=[('ANX', 'Anxiety'), ('DEP', 'Depression')], default='ANX', max_length=3),
        ),
        migrations.AddField(
            model_name='hadsquestion',
            name='weight_0',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hadsquestion',
            name='weight_1',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hadsquestion',
            name='weight_2',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='hadsquestion',
            name='weight_3',
            field=models.IntegerField(default=3),
        ),
    ]
