# Generated by Django 4.2.3 on 2023-07-30 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hads_app', '0008_moodquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoodQuestion',
        ),
    ]
