# Generated by Django 4.2.3 on 2023-07-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hads_app', '0010_subjectivequestion_subjectiveresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectivequestion',
            name='text',
            field=models.TextField(max_length=255),
        ),
    ]
