# Generated by Django 4.2.3 on 2023-07-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hads_app', '0014_alter_subjectiveresponse_test_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='hadstestresult',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
