# Generated by Django 4.2.3 on 2023-08-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hads_app', '0017_alter_subjectiveresponse_test_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectiveresponse',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
