# Generated by Django 4.2.3 on 2023-08-01 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hads_app', '0018_subjectiveresponse_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectiveresponse',
            name='user_name',
        ),
    ]
