# Generated by Django 4.2.3 on 2023-07-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hads_app', '0003_hadschoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hadsquestion',
            name='weight_0',
        ),
        migrations.RemoveField(
            model_name='hadsquestion',
            name='weight_1',
        ),
        migrations.RemoveField(
            model_name='hadsquestion',
            name='weight_2',
        ),
        migrations.RemoveField(
            model_name='hadsquestion',
            name='weight_3',
        ),
        migrations.AlterField(
            model_name='hadsquestion',
            name='subscale',
            field=models.CharField(choices=[('ANX', 'Anxiety'), ('DEP', 'Depression')], max_length=3),
        ),
    ]
