# Generated by Django 4.2.3 on 2023-07-28 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hads_app', '0006_remove_hadschoice_weight_hadsquestion_weight_0_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hadsquestion',
            name='weight_0',
        ),
        migrations.RemoveField(
            model_name='hadsquestion',
            name='weight_1',
        ),
        migrations.RemoveField(
            model_name='hadsquestion',
            name='weight_2',
        ),
        migrations.RemoveField(
            model_name='hadsquestion',
            name='weight_3',
        ),
    ]
