# Generated by Django 4.2.3 on 2023-07-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hads_app', '0007_remove_hadsquestion_weight_0_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
            ],
        ),
    ]
