# Generated by Django 4.2.3 on 2023-07-30 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hads_app', '0011_alter_subjectivequestion_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectiveresponse',
            old_name='user_response',
            new_name='response',
        ),
        migrations.AlterField(
            model_name='subjectivequestion',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subjectiveresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hads_app.subjectivequestion'),
        ),
    ]
