# Generated by Django 4.2.3 on 2023-08-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hads_app', '0015_hadstestresult_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hadstestresult',
            name='name',
        ),
        migrations.AddField(
            model_name='hadstestresult',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
